blank_issues_enabled: false
contact_links:
  - name: Calmpal Questions & Discussions
    url: https://github.com/Corner-Swaps/calmpal/discussions
    about: Ask questions and discuss features with the community.
