// Asset map for React Native / Expo to statically resolve all sounds and images
import { ImageSourcePropType } from 'react-native';

export const SOUND_ASSETS: Record<string, any> = {
  'light-rain': require('../../assets/sounds/light-rain.mp3'),
  'rain-on-leaves': require('../../assets/sounds/rain-on-leaves.mp3'),
  'thunder': require('../../assets/sounds/thunder.mp3'),
  'waves': require('../../assets/sounds/waves.mp3'),
  'waterfall': require('../../assets/sounds/waterfall.mp3'),
  'river': require('../../assets/sounds/river.mp3'),
  'seagulls': require('../../assets/sounds/seagulls.mp3'),
  'birds': require('../../assets/sounds/birds.mp3'),
  'jungle': require('../../assets/sounds/jungle.mp3'),
  'crickets': require('../../assets/sounds/crickets.mp3'),
  'frog': require('../../assets/sounds/frog.mp3'),
  'cat-purring': require('../../assets/sounds/cat-purring.mp3'),
  'wind-in-trees': require('../../assets/sounds/wind-in-trees.mp3'),
  'campfire': require('../../assets/sounds/campfire.mp3'),
  'wind': require('../../assets/sounds/wind.mp3'),
  'howling-wind': require('../../assets/sounds/howling-wind.mp3'),
  'walk-on-leaves': require('../../assets/sounds/walk-on-leaves.mp3'),
  'cafe': require('../../assets/sounds/cafe.mp3'),
  'library': require('../../assets/sounds/library.mp3'),
  'night-village': require('../../assets/sounds/night-village.mp3'),
  'temple': require('../../assets/sounds/temple.mp3'),
  'underwater': require('../../assets/sounds/underwater.mp3'),
  'singing-bowl': require('../../assets/sounds/singing-bowl.mp3'),
  'wind-chimes': require('../../assets/sounds/wind-chimes.mp3'),
  'inside-a-train': require('../../assets/sounds/inside-a-train.mp3'),
  'rain-on-tent': require('../../assets/sounds/rain-on-tent.mp3'),
  'whale': require('../../assets/sounds/whale.mp3'),
  'rain-on-car-roof': require('../../assets/sounds/rain-on-car-roof.mp3'),
  'sailboat': require('../../assets/sounds/sailboat.mp3'),
  'walk-in-snow': require('../../assets/sounds/walk-in-snow.mp3'),
  'clock': require('../../assets/sounds/clock.mp3'),
  'owl': require('../../assets/sounds/owl.mp3'),
  'rowing-boat': require('../../assets/sounds/rowing-boat.mp3'),
  'church': require('../../assets/sounds/church.mp3'),
  'surrender': require('../../assets/sounds/surrender.mp3'),
};

export const IMAGE_ASSETS: Record<string, ImageSourcePropType> = {
  'crickets-night': require('../../assets/images/crickets-night.jpg'),
  'dune-breeze': require('../../assets/images/dune-breeze.jpg'),
  'cozy-campfire': require('../../assets/images/cozy-campfire.jpg'),
  'quiet-library': require('../../assets/images/quiet-library.jpg'),
  'surrender': require('../../assets/images/surrender.jpg'),
  'rolling-thunder': require('../../assets/images/rolling-thunder.jpg'),
  'gentle-rain': require('../../assets/images/gentle-rain.jpg'),
  'ocean-waves': require('../../assets/images/ocean-waves.jpg'),
  'gentle-wind': require('../../assets/images/gentle-wind.jpg'),
  'waterfall': require('../../assets/images/waterfall.jpg'),
  'flowing-river': require('../../assets/images/flowing-river.jpg'),
  'evening-frogs': require('../../assets/images/evening-frogs.jpg'),
  'cat-purr': require('../../assets/images/cat-purr.jpg'),
  'temple-sanctuary': require('../../assets/images/temple-sanctuary.jpg'),
  'coastal-seagulls': require('../../assets/images/coastal-seagulls.jpg'),
  'howling-wind': require('../../assets/images/howling-wind.jpg'),
  'rain-canopy': require('../../assets/images/rain-canopy.jpg'),
  'deep-underwater': require('../../assets/images/deep-underwater.jpg'),
  'tropical-jungle': require('../../assets/images/tropical-jungle.jpg'),
  'night-village': require('../../assets/images/night-village.jpg'),
  'forest-birds': require('../../assets/images/forest-birds.jpg'),
  'walk-leaves': require('../../assets/images/walk-leaves.jpg'),
  'warm-cafe': require('../../assets/images/warm-cafe.jpg'),
  'singing-bowl': require('../../assets/images/singing-bowl.jpg'),
  'wind-chimes': require('../../assets/images/wind-chimes.jpg'),
  'scenic-train': require('../../assets/images/scenic-train.jpg'),
  'rain-on-tent': require('../../assets/images/rain-on-tent.jpg'),
  'ocean-whale': require('../../assets/images/ocean-whale.jpg'),
  'rain-on-car': require('../../assets/images/rain-on-car.jpg'),
  'gentle-sailboat': require('../../assets/images/gentle-sailboat.jpg'),
  'snowy-forest': require('../../assets/images/snowy-forest.jpg'),
  'antique-clock': require('../../assets/images/antique-clock.jpg'),
  'night-owl': require('../../assets/images/night-owl.jpg'),
  'rowing-boat': require('../../assets/images/rowing-boat.jpg'),
  'cathedral-chimes': require('../../assets/images/cathedral-chimes.jpg'),
};

export const THUMB_ASSETS: Record<string, ImageSourcePropType> = {
  'crickets-night-thumb': require('../../assets/images/crickets-night-thumb.jpg'),
  'dune-breeze-thumb': require('../../assets/images/dune-breeze-thumb.jpg'),
  'cozy-campfire-thumb': require('../../assets/images/cozy-campfire-thumb.jpg'),
  'quiet-library-thumb': require('../../assets/images/quiet-library-thumb.jpg'),
  'surrender-thumb': require('../../assets/images/surrender-thumb.jpg'),
  'rolling-thunder-thumb': require('../../assets/images/rolling-thunder-thumb.jpg'),
  'gentle-rain-thumb': require('../../assets/images/gentle-rain-thumb.jpg'),
  'ocean-waves-thumb': require('../../assets/images/ocean-waves-thumb.jpg'),
  'gentle-wind-thumb': require('../../assets/images/gentle-wind-thumb.jpg'),
  'waterfall-thumb': require('../../assets/images/waterfall-thumb.jpg'),
  'flowing-river-thumb': require('../../assets/images/flowing-river-thumb.jpg'),
  'evening-frogs-thumb': require('../../assets/images/evening-frogs-thumb.jpg'),
  'cat-purr-thumb': require('../../assets/images/cat-purr-thumb.jpg'),
  'temple-sanctuary-thumb': require('../../assets/images/temple-sanctuary-thumb.jpg'),
  'coastal-seagulls-thumb': require('../../assets/images/coastal-seagulls-thumb.jpg'),
  'howling-wind-thumb': require('../../assets/images/howling-wind-thumb.jpg'),
  'rain-canopy-thumb': require('../../assets/images/rain-canopy-thumb.jpg'),
  'deep-underwater-thumb': require('../../assets/images/deep-underwater-thumb.jpg'),
  'tropical-jungle-thumb': require('../../assets/images/tropical-jungle-thumb.jpg'),
  'night-village-thumb': require('../../assets/images/night-village-thumb.jpg'),
  'forest-birds-thumb': require('../../assets/images/forest-birds-thumb.jpg'),
  'walk-leaves-thumb': require('../../assets/images/walk-leaves-thumb.jpg'),
  'warm-cafe-thumb': require('../../assets/images/warm-cafe-thumb.jpg'),
  'singing-bowl-thumb': require('../../assets/images/singing-bowl-thumb.jpg'),
  'wind-chimes-thumb': require('../../assets/images/wind-chimes-thumb.jpg'),
  'scenic-train-thumb': require('../../assets/images/scenic-train-thumb.jpg'),
  'rain-on-tent-thumb': require('../../assets/images/rain-on-tent-thumb.jpg'),
  'ocean-whale-thumb': require('../../assets/images/ocean-whale-thumb.jpg'),
  'rain-on-car-thumb': require('../../assets/images/rain-on-car-thumb.jpg'),
  'gentle-sailboat-thumb': require('../../assets/images/gentle-sailboat-thumb.jpg'),
  'snowy-forest-thumb': require('../../assets/images/snowy-forest-thumb.jpg'),
  'antique-clock-thumb': require('../../assets/images/antique-clock-thumb.jpg'),
  'night-owl-thumb': require('../../assets/images/night-owl-thumb.jpg'),
  'rowing-boat-thumb': require('../../assets/images/rowing-boat-thumb.jpg'),
  'cathedral-chimes-thumb': require('../../assets/images/cathedral-chimes-thumb.jpg'),
};
